version: "3"
services:
    web:
        build: .
        container_name: parisavelo 
        labels: 
            - "traefik.enable=true"
            - "traefik.http.routers.parisavelo-secured.entrypoints=websecure"
            - "traefik.http.routers.parisavelo-secured.rule=Host(`parisavelo.leverry.fr`)"
            - "traefik.http.routers.parisavelo-secured.tls.certresolver=myhttpchallenge"
            #redirection 
            - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.parisavelo.rule=Host(`parisavelo.leverry.fr`)"
            - "traefik.http.routers.parisavelo.entrypoints=web"
            - "traefik.http.routers.parisavelo.middlewares=redirect"
        networks: 
            - "web"
networks: 
    web: 
        external: true